### ISSUE TITLE
Have you tested the package on CTA panel?

### ISSUE THREAD

**Issue by yeswzc** [DavisLaboratory/GeoMXAnalysisWorkflow#5]
which has ~1800 genes only.

**Comment by ningbioinfo** [comment]
Yes, for CTA panel, the size factor normalisation instead of TMM is recommend, or if you have batch-effect in your data, you can still use RUV-4.

**Comment by yeswzc** [comment]
> Yes, for CTA panel, the size factor normalisation instead of TMM is recommend, or if you have batch-effect in your data, you can still use RUV-4.

I see. Thank you!

**Comment by ningbioinfo** [comment]
Hi @joonlee3 , the tutorial in this repo is using WTA as examples, for the other questions, size factor or TMM when you don't have batch effect, otherwise you need batch removal normalization, negative control probes have been used to in the probeQC stage, so would not be helpful in the normalization, for details can have a look at our paper in the biorxiv: https://www.biorxiv.org/content/10.1101/2023.04.23.538017v1
